### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kamlesh-ai**

### CODE REVIEW

**Comment by kishanpatel13** [comment]
Can one of the admins verify this patch?

**Comment by kamlesh-ai** [comment]
ok to test

**Comment by kamlesh-ai** [comment]
ok to test

**Comment by kamlesh-ai** [comment]
ok to test

**Comment by kamlesh-ai** [comment]
ok to test

**Comment by kamlesh-ai** [comment]
ok to test

**Comment by kamlesh-ai** [comment]
ok to test

**Comment by kamlesh-ai** [comment]
ok to test

**Pull request closed without merging**
